### ISSUE TITLE
profile switching got slow

### ISSUE THREAD

**Issue by dev1981** [terrymacdonald/NVIDIAInfo#3]
hi sir,

today i downloaded the latest version of nvidiainfo, re-created my profiles. Switching works as expected but it takes very very long.
I upgraded from 1.7.5 were the profile switch worked nearly instant for me.
Dont really know if its by design now.
I attached the log.
[NVIDIAInfo.log](https://github.com/terrymacdonald/NVIDIAInfo/files/9023125/NVIDIAInfo.log)

best regards

**Comment by dev1981** [comment]
Hi Sir, 

did u had little time to look into that? if i can support, please feel free to contact me.

regards

**Comment by terrymacdonald** [comment]
Sorry @dev1981, I only noticed this here now. I expect that was related to the taskbar location detection functionality that I added previously. This was slower specifically due to windows delaying when it wrote the taskbar location settings to windows registry. The delay was that we needed to wait until Windows wrote to the registry before we could get the windows taskbar registry settings, and Windows took up to 20 seconds :(. 

This windows taskbar location functionality has been disabled from 1.8.4 onwards, in the interests of speed. I still hope to add Windows taskbar location detection back into a future version of the WinLibrary, but only if I can find a way that doesn't slow it down.

Please download the latest version of 1.8.4 as it should be much faster now.

Thanks
Terry
